version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
